### PR TITLE
Fix broken backspace behaviour between fields

### PR DESCRIPTION
**Pull request by noamnelke**
This PR addresses https://github.com/stripe/PaymentKit/issues/39

### Summary of issue
If a user makes a mistake when entering the expiration date and uses backspace to delete the  leftmost character of the expiration date, the caret moves to the end of the card number field and an animation left is triggered, sliding the expiration date and cvc fields out of view.

Since the caret is at the end of the card number field (that's already at full length) no more characters can be entered and the user is "stuck" in this situation. The only way to return to the expiration date is to delete the rightmost character of the card number and re-enter it (hardly intuitive).

### Solution
When a user deletes the leftmost character of the expiration date field - move the caret to the end of the card number field, but don't trigger the animation left, until the user actually deletes a character. This allows the user to tap the expiration date field to return to it.

Additionally, when the caret is at the end of the card number field or expiration date field and the user types more text - move the caret to the beginning of the next field and try to insert that text.

### CODE REVIEW

**Comment by noamnelke** [comment]
hey, @jflinter, any chance this will be merged soon?

**Comment by jflinter** [comment]
Hey @noamnelke, thanks for the PR.
I'm looking into doing a lot of cleanup around this repo, as it's been pretty unmaintained for a while, but that may end up taking the form of some pretty serious architectural improvements. I'm going to hold off on merging/closing this (and other) PRs until we have a better sense of how things are going to look. Either way, thank you for opening this, and I'll update here when we have a better sense of things.

**Comment by noamnelke** [comment]
Hi @jflinter, thanks for the reply!

Given the UI has some pretty complex behaviour I hope you're taking testability into account for the new architecture.

**Comment by jflinter** [comment]
Ohhh yeahhhh : )

**Comment by jflinter** [comment]
Hey @noamnelke - I've just merged our rewrite over at https://github.com/stripe/stripe-ios (where `PTKView` has now been replaced with `STPPaymentCardTextField`). I hope you enjoy it!

**Comment by noamnelke** [comment]
Nice!

Didn't look at the code yet, but I ran the sample app and it looks good.

The current behaviour is better than the old, but I think my solution is still better. When a user taps the card number the full number scrolls into view with no obvious option to scroll back to the other fields (with the cursor after the last digit of the card number tapping any number scrolls there, but this is hardly obvious or expected).

My solution was to not scroll the full card number into view unless one of its digits was deleted, which is also not perfect (what if I just want to look at the full number again?), but creates a consistent behaviour: if a full, valid card number is entered it's scrolled out of view, otherwise this field is the only one visible.

Another (maybe better?) option would be to add some kind of UI element (like a right arrow) to the right of the card number field that lets the user scroll to the other fields. This can become visible only if the card number is valid and fully visible (basically, only in case the user typed a full valid number and then tapped the last 4 digits to scroll back to it).

Sorry for the long comment... ¯\_(ツ)_/¯

**Comment by jflinter** [comment]
Hey @noamnelke - thanks for the feedback. I agree that there are some edge cases that aren't handled ideally, but want to make sure that they're actually an issue in practice before iterating here. I've added this to our list of things to revisit down the line - in the meantime, we're going to wait for a few weeks and see if people have other feature requests/considerations.

**Comment by noamnelke** [comment]
:+1: 

Another thing to put in your backlog is editing behaviour. Putting the cursor anywhere other than the end of a field and typing / deleting results in the cursor jumping to the end of the field, making editing nearly impossible.

**Pull request closed without merging**
